spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: spring-mongodb
      port: 27017
      host: mongodb.mongodb.svc.cluster.local
      #      uri:

management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true